version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"  # adjust the port if your app uses a different one
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
